package compiler.gals;

public interface Constants extends ScannerConstants, ParserConstants
{
    int EPSILON  = 0;
    int DOLLAR   = 1;

    int t_variable = 2;
    int t_char = 3;
    int t_string = 4;
    int t_bool = 5;
    int t_short = 6;
    int t_int = 7;
    int t_long = 8;
    int t_float = 9;
    int t_double = 10;
    int t_decimal = 11;
    int t_if = 12;
    int t_elif = 13;
    int t_else = 14;
    int t_while = 15;
    int t_for = 16;
    int t_do = 17;
    int t_return = 18;
    int t_read = 19;
    int t_write = 20;
    int t_number = 21;
    int t_binary_number = 22;
    int t_hex_number = 23;
    int t_real_number = 24;
    int t_char_literal = 25;
    int t_string_literal = 26;
    int t_true = 27;
    int t_false = 28;
    int t_null = 29;
    int t_bit_shift_left = 30;
    int t_bit_shift_right = 31;
    int t_bit_and = 32;
    int t_bit_or = 33;
    int t_bit_xor = 34;
    int t_bit_not = 35;
    int t_and = 36;
    int t_or = 37;
    int t_not = 38;
    int t_greater_than = 39;
    int t_less_than = 40;
    int t_greater_equal = 41;
    int t_less_equal = 42;
    int t_equality = 43;
    int t_inequality = 44;
    int t_equals = 45;
    int t_addition = 46;
    int t_subtraction = 47;
    int t_multiplication = 48;
    int t_division = 49;
    int t_remainder = 50;
    int t_increment = 51;
    int t_decrement = 52;
    int t_addition_equals = 53;
    int t_subtraction_equals = 54;
    int t_multiplication_equals = 55;
    int t_division_equals = 56;
    int t_modulus_equals = 57;
    int t_open_parentheses = 58;
    int t_close_parentheses = 59;
    int t_open_bracket = 60;
    int t_close_bracket = 61;
    int t_open_brace = 62;
    int t_close_brace = 63;
    int t_comma = 64;
    int t_colon = 65;
    int t_dot = 66;
    int t_semicolon = 67;
    int t_void = 68;

}
