package compiler.enums;

public enum OperationType {
    BitShiftLeft,
    BitShiftRight,
    BitAnd,
    BitOr,
    BitXor,
    BitNot,
    And,
    Or,
    Not,
    GreaterThan,
    LessThan,
    GreaterEqual,
    LessEqual,
    Equality,
    Inequality,
    Equals,
    Addition,
    Subtraction,
    Multiplication,
    Division,
    Remainder,
    Increment,
    Decrement,
    AdditionEquals,
    SubtractionEquals,
    MultiplicationEquals,
    DivisionEquals,
    RemainderEquals,
}
